openapi: 3.0.0
info:
  title: Profile Management API
  version: 1.0.0
  description: API contracts for profile management operations

paths:
  /api/v1/profile:
    get:
      summary: Get user profile information
      responses:
        '200':
          description: User profile retrieved successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UserProfile'
        '401':
          $ref: '#/components/responses/Unauthorized'

    put:
      summary: Update user profile information
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UpdateProfileRequest'
      responses:
        '200':
          description: Profile updated successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UpdateProfileResponse'
        '400':
          $ref: '#/components/responses/BadRequest'
        '401':
          $ref: '#/components/responses/Unauthorized'

  /api/v1/profile/password:
    post:
      summary: Change user password
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ChangePasswordRequest'
      responses:
        '200':
          description: Password changed successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ChangePasswordResponse'
        '400':
          $ref: '#/components/responses/BadRequest'
        '401':
          $ref: '#/components/responses/Unauthorized'

  /api/v1/profile/email:
    post:
      summary: Update user email
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UpdateEmailRequest'
      responses:
        '200':
          description: Email updated successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UpdateEmailResponse'
        '400':
          $ref: '#/components/responses/BadRequest'
        '401':
          $ref: '#/components/responses/Unauthorized'

components:
  schemas:
    UserProfile:
      type: object
      properties:
        id:
          type: string
          description: User identifier
        username:
          type: string
          description: User's username
        email:
          type: string
          description: User's email address
        created_at:
          type: string
          format: date-time
          description: Account creation timestamp
        updated_at:
          type: string
          format: date-time
          description: Last update timestamp
      required:
        - id
        - username
        - email
        - created_at
        - updated_at

    UpdateProfileRequest:
      type: object
      properties:
        username:
          type: string
          minLength: 1
          maxLength: 50
      required:
        - username

    UpdateProfileResponse:
      type: object
      properties:
        success:
          type: boolean
        message:
          type: string
        data:
          $ref: '#/components/schemas/UserProfile'

    ChangePasswordRequest:
      type: object
      properties:
        current_password:
          type: string
          description: User's current password
          minLength: 8
        new_password:
          type: string
          description: New password
          minLength: 8
        confirm_new_password:
          type: string
          description: Confirmation of new password
          minLength: 8
      required:
        - current_password
        - new_password
        - confirm_new_password

    ChangePasswordResponse:
      type: object
      properties:
        success:
          type: boolean
        message:
          type: string

    UpdateEmailRequest:
      type: object
      properties:
        new_email:
          type: string
          format: email
          description: New email address
        password:
          type: string
          description: Current password for verification
          minLength: 8
      required:
        - new_email
        - password

    UpdateEmailResponse:
      type: object
      properties:
        success:
          type: boolean
        message:
          type: string

    Error:
      type: object
      properties:
        error:
          type: string
        message:
          type: string

  responses:
    Unauthorized:
      description: Authentication required
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
    BadRequest:
      description: Invalid request data
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'